// Shadow root sets shared between Cabane.js (single-instance nodes) and groupInstancing.js (instanced nodes).
// Add an object here when it should cast or receive shadows in both pipelines.
// Single-instance-only objects (hut01, trunk, etc.) are added directly in Cabane.js.
// Instanced-only specifics (house receiver, excluded groups) stay in groupInstancing.js.

export const SHARED_SHADOW_CASTER_ROOTS = new Set([
  'backgroundTree',
  'juicemachine',
  'juiceglass',
  'ladder',
  'stairs01',
  'stairs02',
  'welcome01',
  'railling',
  'railling-hut',
  'timeatm',
  'hill',
  'bulding',
  'lampe',
  'lampe-mushroom',
  'cabinet',
  'shelves',
  'counter01',
  'armchair',
  'chair',
  'chair-large',
  'littletable',
  'stool',
  'basket',
  'drawing',
  'hearth',
  'plant01',
  'plant01-1',
  'plant02',
  'plant02-1',
  'plant03',
  'plant04',
  'plant05',
  'plant06',
  'plant08',
  'plant08-1',
  'rug01',
  'rug02',
])

export const SHARED_SHADOW_RECEIVER_ROOTS = new Set([
  'lampe',
  'lampe-mushroom',
  'plant01',
  'plant01-1',
  'plant02',
  'plant02-1',
  'plant03',
  'plant04',
  'plant05',
  'plant06',
  'plant08',
  'plant08-1',
  'counter01',
  'shelves',
  'cabinet',
  'armchair',
  'chair',
  'chair-large',
  'littletable',
  'stool',
  'basket',
  'drawing',
  'hearth',
  'rug01',
  'rug02',
])
